### ISSUE TITLE
memory leak prevention kills the portal

### ISSUE THREAD

**Issue by tomvanoppens** [ibm-datapower/appliance-management-center#2]
SEVERE: The web application [/amc] registered the JDBC driver [org.apache.derby.jdbc.AutoloadedDriver40] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
SEVERE: The web application [/amc] created a ThreadLocal with key of type [org.apache.xmlbeans.impl.schema.SchemaTypeLoaderImpl$SchemaTypeLoaderCache$1](value [org.apache.xmlbeans.impl.schema.SchemaTypeLoaderImpl$SchemaTypeLoaderCache$1@29102d8e]) and a value of type [java.util.ArrayList](value [[java.lang.ref.SoftReference@651edab1]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
SEVERE: The web application [/amc] created a ThreadLocal with key of type [org.apache.xmlbeans.XmlBeans$1](value [org.apache.xmlbeans.XmlBeans$1@4ca7ce54]) and a value of type [java.lang.ref.SoftReference](value [java.lang.ref.SoftReference@1cdb141d]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
SEVERE: The web application [/amc] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@73058ab7]) and a value of type [org.apache.derby.iapi.services.context.ContextManager](value [org.apache.derby.iapi.services.context.ContextManager@604806e0]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
[user@dpportal ~]$ cat logs/catalina.out |grep SEV
SEVERE: The web application [/amc] registered the JDBC driver [org.apache.derby.jdbc.AutoloadedDriver40] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
SEVERE: The web application [/amc] created a ThreadLocal with key of type [org.apache.xmlbeans.impl.schema.SchemaTypeLoaderImpl$SchemaTypeLoaderCache$1](value [org.apache.xmlbeans.impl.schema.SchemaTypeLoaderImpl$SchemaTypeLoaderCache$1@29102d8e]) and a value of type [java.util.ArrayList](value [[java.lang.ref.SoftReference@651edab1]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
SEVERE: The web application [/amc] created a ThreadLocal with key of type [org.apache.xmlbeans.XmlBeans$1](value [org.apache.xmlbeans.XmlBeans$1@4ca7ce54]) and a value of type [java.lang.ref.SoftReference](value [java.lang.ref.SoftReference@1cdb141d]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
SEVERE: The web application [/amc] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@73058ab7]) and a value of type [org.apache.derby.iapi.services.context.ContextManager](value [org.apache.derby.iapi.services.context.ContextManager@604806e0]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by ghost** [comment]
I've seen these error messages but they are just warnings that the shutdown wasn't as clean. I have not investigated if a newer version of Derby solves some of those issues but I don't see anything in the above that implies that the application itself didn't work.
